// What  do the following error message and stack trace tell you?

// (refer to exercise 2 to get error message)

// The stack output is saying thhat at line 4, character 15, a reference error is being
// thrown. That is, the error is triggered at that point in the code. At hello
// suggests that the error was thrown inside the hello function scope, and the
// at object reference indicates that hello was called from line 13 at the first
// character in the program at the global level. The rest of the output
// comes from node.
